package net.nhatjs.js_furniture_mod.core;

import net.fabricmc.fabric.api.itemgroup.v1.FabricItemGroup;
import net.minecraft.item.ItemGroup;
import net.minecraft.item.ItemStack;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.text.Text;
import net.minecraft.util.Identifier;
import net.nhatjs.js_furniture_mod.NhatJSFurnitureMod;

public class ModItemGroups {
    public static final ItemGroup JS_FURNITURE_ITEMS_GROUP = Registry.register(Registries.ITEM_GROUP,
            Identifier.of(NhatJSFurnitureMod.MOD_ID, "js_furniture_logo"),
            FabricItemGroup.builder().icon(() -> new ItemStack(ModBlocks.BLACK_TABLE))
                    .displayName(Text.translatable("itemgroup.js_furniture_mod.js_furniture_tab"))
                    .entries((displayContext, entries) -> {
                        entries.add(ModBlocks.WOOD_LIGHT_CHAIR);
                        entries.add(ModBlocks.WOOD_MEDIUM_CHAIR);
                        entries.add(ModBlocks.BLACK_CHAIR);
                        entries.add(ModBlocks.WHITE_CHAIR);
                        entries.add(ModBlocks.BLACK_SOFA);
                        entries.add(ModBlocks.WHITE_SOFA);
                        entries.add(ModBlocks.WOOD_LIGHT_TABLE);
                        entries.add(ModBlocks.WOOD_MEDIUM_TABLE);
                        entries.add(ModBlocks.BLACK_TABLE);
                        entries.add(ModBlocks.WHITE_TABLE);
                        entries.add(ModBlocks.WOOD_LIGHT_COFFEE_TABLE);
                        entries.add(ModBlocks.WOOD_MEDIUM_COFFEE_TABLE);
                        entries.add(ModBlocks.BLACK_COFFEE_TABLE);
                        entries.add(ModBlocks.WHITE_COFFEE_TABLE);
                        entries.add(ModBlocks.WOOD_LIGHT_DESK);
                        entries.add(ModBlocks.WOOD_MEDIUM_DESK);
                        entries.add(ModBlocks.BLACK_DESK);
                        entries.add(ModBlocks.WHITE_DESK);
                        entries.add(ModBlocks.WOOD_LIGHT_STANDING_DESK);
                        entries.add(ModBlocks.WOOD_MEDIUM_STANDING_DESK);
                        entries.add(ModBlocks.BLACK_STANDING_DESK);
                        entries.add(ModBlocks.WHITE_STANDING_DESK);
                        entries.add(ModBlocks.WOOD_LIGHT_STANDING_DESK_B);
                        entries.add(ModBlocks.WOOD_MEDIUM_STANDING_DESK_B);
                        entries.add(ModBlocks.BLACK_STANDING_DESK_B);
                        entries.add(ModBlocks.WHITE_STANDING_DESK_B);
                        entries.add(ModBlocks.WOOD_LIGHT_3_DRAWER_DRESSER);
                        entries.add(ModBlocks.WOOD_MEDIUM_3_DRAWER_DRESSER);
                        entries.add(ModBlocks.BLACK_3_DRAWER_DRESSER);
                        entries.add(ModBlocks.WHITE_3_DRAWER_DRESSER);
                        entries.add(ModBlocks.WOOD_LIGHT_TV_STAND);
                        entries.add(ModBlocks.WOOD_MEDIUM_TV_STAND);
                        entries.add(ModBlocks.BLACK_TV_STAND);
                        entries.add(ModBlocks.WHITE_TV_STAND);
                        entries.add(ModBlocks.WOOD_LIGHT_KITCHEN_CABINET_BOTTOM);
                        entries.add(ModBlocks.WOOD_LIGHT_KITCHEN_CABINET_BOTTOM_WITH_SINK);
                        entries.add(ModBlocks.WOOD_LIGHT_KITCHEN_CABINET_BOTTOM_2);
                        entries.add(ModBlocks.WOOD_LIGHT_KITCHEN_CABINET_BOTTOM_2_EXTRA);
                        entries.add(ModBlocks.WOOD_LIGHT_KITCHEN_CABINET_BOTTOM_B);
                        entries.add(ModBlocks.WOOD_LIGHT_KITCHEN_CABINET_BOTTOM_B_WITH_SINK);
                        entries.add(ModBlocks.WOOD_LIGHT_KITCHEN_CABINET_BOTTOM_B_2);
                        entries.add(ModBlocks.WOOD_LIGHT_KITCHEN_DRAWERS);
                        entries.add(ModBlocks.WOOD_LIGHT_KITCHEN_DRAWERS_B);
                        entries.add(ModBlocks.WOOD_LIGHT_KITCHEN_CABINET_TOP);
                        entries.add(ModBlocks.WOOD_LIGHT_KITCHEN_CABINET_TOP_B);
                        entries.add(ModBlocks.WOOD_MEDIUM_KITCHEN_CABINET_BOTTOM);
                        entries.add(ModBlocks.WOOD_MEDIUM_KITCHEN_CABINET_BOTTOM_WITH_SINK);
                        entries.add(ModBlocks.WOOD_MEDIUM_KITCHEN_CABINET_BOTTOM_2);
                        entries.add(ModBlocks.WOOD_MEDIUM_KITCHEN_CABINET_BOTTOM_2_EXTRA);
                        entries.add(ModBlocks.WOOD_MEDIUM_KITCHEN_CABINET_BOTTOM_B);
                        entries.add(ModBlocks.WOOD_MEDIUM_KITCHEN_CABINET_BOTTOM_B_WITH_SINK);
                        entries.add(ModBlocks.WOOD_MEDIUM_KITCHEN_CABINET_BOTTOM_B_2);
                        entries.add(ModBlocks.WOOD_MEDIUM_KITCHEN_DRAWERS);
                        entries.add(ModBlocks.WOOD_MEDIUM_KITCHEN_DRAWERS_B);
                        entries.add(ModBlocks.WOOD_MEDIUM_KITCHEN_CABINET_TOP);
                        entries.add(ModBlocks.WOOD_MEDIUM_KITCHEN_CABINET_TOP_B);
                        entries.add(ModBlocks.BLACK_MIRROR);
                        entries.add(ModBlocks.BLACK_VERTICAL_BLINDS);
                        entries.add(ModBlocks.WHITE_VERTICAL_BLINDS);
                        entries.add(ModBlocks.WOOD_LIGHT_CEILING_FAN_BLACK);
                        entries.add(ModBlocks.WOOD_MEDIUM_CEILING_FAN_BLACK);
                        entries.add(ModBlocks.BLACK_CEILING_FAN_BLACK);
                        entries.add(ModBlocks.WHITE_CEILING_FAN_BLACK);
                        entries.add(ModBlocks.WOOD_LIGHT_CEILING_FAN_WHITE);
                        entries.add(ModBlocks.WOOD_MEDIUM_CEILING_FAN_WHITE);
                        entries.add(ModBlocks.BLACK_CEILING_FAN_WHITE);
                        entries.add(ModBlocks.WHITE_CEILING_FAN_WHITE);
                        entries.add(ModBlocks.SOCKET);
                        entries.add(ModBlocks.TV);
                        entries.add(ModBlocks.FLOOR_STANDING_SPEAKER);
                        entries.add(ModBlocks.MODERN_CLOCK);
                        entries.add(ModBlocks.MODERN_LIGHT);
                        entries.add(ModBlocks.LED_FLOOR_LAMP);
                        entries.add(ModBlocks.LED_FLOOR_LAMP_RGB_OFF);
                        entries.add(ModBlocks.LED_RGB_TRIANGLE_PANEL);
                        entries.add(ModBlocks.STUDIO_LIGHT);
                        entries.add(ModBlocks.BLACK_GAMING_CHAIR);
                        entries.add(ModBlocks.WHITE_GAMING_CHAIR);
                        entries.add(ModBlocks.MONITOR_SETUP);
                        entries.add(ModBlocks.MONITOR);
                        entries.add(ModBlocks.BLACK_KEYBOARD);
                        entries.add(ModBlocks.BLACK_COMPUTER_MOUSE);
                        entries.add(ModBlocks.PC);
                        entries.add(ModBlocks.PC_TOWER_GLASS);
                        entries.add(ModBlocks.LAPTOP);
                        entries.add(ModBlocks.PORTABLE_LAPTOP_STAND);
                        entries.add(ModBlocks.LAPTOP_CLOSED_PORTABLE_LAPTOP_STAND);
                        entries.add(ModBlocks.MIDI_KEYBOARD_CONTROLLER);
                        entries.add(ModBlocks.MIDI_STANDALONE_GROOVEBOX);
                        entries.add(ModBlocks.MIDI_STANDALONE_GROOVEBOX_2);
                        entries.add(ModBlocks.MIDI_STANDALONE_GROOVEBOX_3);
                        entries.add(ModBlocks.COOKTOP);
                        entries.add(ModBlocks.FRIDGE_A);
                        entries.add(ModBlocks.FRIDGE_B);
                        entries.add(ModBlocks.MODERN_BATHROOM_SINK_STORAGE);
                        entries.add(ModBlocks.MODERN_BATHROOM_MIRROR_SHELF);
                        entries.add(ModBlocks.SHOWER);
                        entries.add(ModBlocks.TOILET);
                        entries.add(ModBlocks.WASHING_MACHINE_AI);
                        entries.add(ModBlocks.PLANT_POT);
                        entries.add(ModBlocks.BOOKS);
                        entries.add(ModItems.WOOD_LIGHT_SQUARE_STICK);
                        entries.add(ModItems.WOOD_MEDIUM_SQUARE_STICK);
                        entries.add(ModItems.BLACK_SQUARE_STICK);
                        entries.add(ModItems.WHITE_SQUARE_STICK);
                        entries.add(ModItems.WOOD_LIGHT_SHORT_SQUARE_STICK);
                        entries.add(ModItems.WOOD_MEDIUM_SHORT_SQUARE_STICK);
                        entries.add(ModItems.BLACK_SHORT_SQUARE_STICK);
                        entries.add(ModItems.WHITE_SHORT_SQUARE_STICK);
                        entries.add(ModItems.WOOD_LIGHT_PANEL);
                        entries.add(ModItems.WOOD_MEDIUM_PANEL);
                        entries.add(ModItems.BLACK_PANEL);
                        entries.add(ModItems.WHITE_PANEL);
                        entries.add(ModBlocks.WOOD_LIGHT_DRAWER_SINGLE);
                        entries.add(ModBlocks.WOOD_MEDIUM_DRAWER_SINGLE);
                        entries.add(ModBlocks.BLACK_DRAWER_SINGLE);
                        entries.add(ModBlocks.WHITE_DRAWER_SINGLE);
                        entries.add(ModBlocks.BLACK_DESK_COLUMN);
                        entries.add(ModBlocks.WHITE_DESK_COLUMN);
                        entries.add(ModBlocks.WOOD_LIGHT_COMPARTMENT_STORAGE_CABINET);
                        entries.add(ModBlocks.WOOD_MEDIUM_COMPARTMENT_STORAGE_CABINET);
                        entries.add(ModBlocks.BLACK_COMPARTMENT_STORAGE_CABINET);
                        entries.add(ModBlocks.WHITE_COMPARTMENT_STORAGE_CABINET);
                        entries.add(ModBlocks.WOOD_LIGHT_KITCHEN_COMPARTMENT_STORAGE_CABINET);
                        entries.add(ModBlocks.WOOD_MEDIUM_KITCHEN_COMPARTMENT_STORAGE_CABINET);
                        entries.add(ModBlocks.WOOD_LIGHT_KITCHEN_COMPARTMENT_STORAGE_CABINET_B);
                        entries.add(ModBlocks.WOOD_MEDIUM_KITCHEN_COMPARTMENT_STORAGE_CABINET_B);
                        entries.add(ModItems.REMOTE_CONTROL_RGB);
                        entries.add(ModBlocks.COMPUTER_CASE);
                        entries.add(ModItems.CPU);
                        entries.add(ModItems.MAINBOARD);
                        entries.add(ModItems.RAM);
                        entries.add(ModItems.AIO_COOLER);
                        entries.add(ModItems.COMPUTER_FAN);
                        entries.add(ModItems.GPU);
                        entries.add(ModItems.PSU);
                    }).build());

    public static final ItemGroup JS_FURNITURE_GARBAGE_ITEMS_GROUP = Registry.register(Registries.ITEM_GROUP,
            Identifier.of(NhatJSFurnitureMod.MOD_ID, "js_furniture_trash"),
            FabricItemGroup.builder().icon(() -> new ItemStack(ModItems.GARBAGE_ITEM))
                    .displayName(Text.translatable("itemgroup.js_furniture_mod.js_trash_furniture_tab"))
                    .entries((displayContext, entries) -> {
                        entries.add(ModBlocks.WOOD_CHAIR);
                        entries.add(ModBlocks.WOOD_COFFEE_TABLE);
                        entries.add(ModBlocks.WOOD_DESK);
                        entries.add(ModBlocks.WOOD_STANDING_DESK);
                        entries.add(ModBlocks.WOOD_STANDING_DESK_B);
                        entries.add(ModBlocks.WOOD_3_DRAWER_DRESSER);
                        entries.add(ModBlocks.KITCHEN_CABINET_BOTTOM);
                        entries.add(ModBlocks.KITCHEN_CABINET_BOTTOM_WITH_SINK);
                        entries.add(ModBlocks.KITCHEN_CABINET_BOTTOM_2);
                        entries.add(ModBlocks.KITCHEN_CABINET_BOTTOM_2_EXTRA);
                        entries.add(ModBlocks.KITCHEN_CABINET_BOTTOM_B);
                        entries.add(ModBlocks.KITCHEN_CABINET_BOTTOM_B_WITH_SINK);
                        entries.add(ModBlocks.KITCHEN_CABINET_BOTTOM_B_2);
                        entries.add(ModBlocks.KITCHEN_DRAWERS);
                        entries.add(ModBlocks.KITCHEN_DRAWERS_B);
                        entries.add(ModBlocks.KITCHEN_CABINET_TOP);
                        entries.add(ModBlocks.KITCHEN_CABINET_TOP_B);
                        entries.add(ModBlocks.CEILING_FAN);
                        entries.add(ModBlocks.CEILING_FAN_B);
                        entries.add(ModBlocks.WOOD_STRIPED_WALL);
                        entries.add(ModBlocks.WOOD_MEDIUM_STRIPED_WALL);
                        entries.add(ModBlocks.SOFA);
                        entries.add(ModBlocks.MODERN_CHAIR);
                        entries.add(ModBlocks.VERTICAL_BLINDS);
                        entries.add(ModBlocks.KEYBOARD);
                        entries.add(ModBlocks.COMPUTER_MOUSE);
                    }).build());

    public static void registerItemGroups() {
        NhatJSFurnitureMod.LOGGER.info("Registering Item Groups for " + NhatJSFurnitureMod.MOD_ID);
    }
}
