package net.nhatjs.js_furniture_mod.datagen;

import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricBlockLootTableProvider;
import net.minecraft.registry.RegistryWrapper;
import net.nhatjs.js_furniture_mod.core.ModBlocks;
import java.util.concurrent.CompletableFuture;

public class ModLootTableProvider extends FabricBlockLootTableProvider {
    public ModLootTableProvider(FabricDataOutput dataOutput, CompletableFuture<RegistryWrapper.WrapperLookup> registryLookup) {
        super(dataOutput, registryLookup);
    }

    @Override
    public void generate() {
        addDrop(ModBlocks.WOOD_CHAIR);
        addDrop(ModBlocks.WHITE_CHAIR);
        addDrop(ModBlocks.MODERN_CHAIR);
        addDrop(ModBlocks.SOFA);
        addDrop(ModBlocks.WOOD_LIGHT_TABLE);
        addDrop(ModBlocks.BLACK_TABLE);
        addDrop(ModBlocks.WHITE_TABLE);
        addDrop(ModBlocks.WOOD_COFFEE_TABLE);
        addDrop(ModBlocks.WHITE_COFFEE_TABLE);
        addDrop(ModBlocks.WOOD_DESK);
        addDrop(ModBlocks.WHITE_DESK);
        addDrop(ModBlocks.WOOD_STANDING_DESK);
        addDrop(ModBlocks.WOOD_STANDING_DESK_B);
        addDrop(ModBlocks.BLACK_STANDING_DESK);
        addDrop(ModBlocks.BLACK_STANDING_DESK_B);
        addDrop(ModBlocks.WHITE_STANDING_DESK);
        addDrop(ModBlocks.WHITE_STANDING_DESK_B);
        addDrop(ModBlocks.WOOD_3_DRAWER_DRESSER);
        addDrop(ModBlocks.WHITE_3_DRAWER_DRESSER);
        addDrop(ModBlocks.WOOD_LIGHT_TV_STAND);
        addDrop(ModBlocks.WHITE_TV_STAND);
        addDrop(ModBlocks.KITCHEN_CABINET_BOTTOM);
        addDrop(ModBlocks.KITCHEN_CABINET_BOTTOM_WITH_SINK);
        addDrop(ModBlocks.KITCHEN_CABINET_BOTTOM_2);
        addDrop(ModBlocks.KITCHEN_CABINET_BOTTOM_2_EXTRA);
        addDrop(ModBlocks.KITCHEN_CABINET_BOTTOM_B);
        addDrop(ModBlocks.KITCHEN_CABINET_BOTTOM_B_WITH_SINK);
        addDrop(ModBlocks.KITCHEN_CABINET_BOTTOM_B_2);
        addDrop(ModBlocks.KITCHEN_DRAWERS);
        addDrop(ModBlocks.KITCHEN_DRAWERS_B);
        addDrop(ModBlocks.KITCHEN_CABINET_TOP);
        addDrop(ModBlocks.KITCHEN_CABINET_TOP_B);
        addDrop(ModBlocks.WOOD_STRIPED_WALL);
        addDrop(ModBlocks.BLACK_MIRROR);
        addDrop(ModBlocks.VERTICAL_BLINDS);
        addDrop(ModBlocks.SOCKET);
        addDrop(ModBlocks.TV);
        addDrop(ModBlocks.FLOOR_STANDING_SPEAKER);
        addDrop(ModBlocks.MODERN_CLOCK);
        addDrop(ModBlocks.MODERN_LIGHT);
        addDrop(ModBlocks.LED_FLOOR_LAMP);
        addDrop(ModBlocks.LED_FLOOR_LAMP_RGB_OFF);
        addDrop(ModBlocks.LED_RGB_TRIANGLE_PANEL);
        addDrop(ModBlocks.STUDIO_LIGHT);
        addDrop(ModBlocks.MONITOR_SETUP);
        addDrop(ModBlocks.MONITOR);
        addDrop(ModBlocks.KEYBOARD);
        addDrop(ModBlocks.COMPUTER_MOUSE);
        addDrop(ModBlocks.PC);
        addDrop(ModBlocks.PC_RGB1_OFF);
        addDrop(ModBlocks.LAPTOP);
        addDrop(ModBlocks.PORTABLE_LAPTOP_STAND);
        addDrop(ModBlocks.LAPTOP_CLOSED_PORTABLE_LAPTOP_STAND);
        addDrop(ModBlocks.MIDI_STANDALONE_GROOVEBOX);
        addDrop(ModBlocks.MIDI_STANDALONE_GROOVEBOX_2);
        addDrop(ModBlocks.MIDI_STANDALONE_GROOVEBOX_3);
        addDrop(ModBlocks.COOKTOP);
        addDrop(ModBlocks.FRIDGE_A);
        addDrop(ModBlocks.FRIDGE_B);
        addDrop(ModBlocks.MODERN_BATHROOM_SINK_STORAGE);
        addDrop(ModBlocks.MODERN_BATHROOM_MIRROR_SHELF);
        addDrop(ModBlocks.SHOWER);
        addDrop(ModBlocks.WASHING_MACHINE_AI);
        addDrop(ModBlocks.PLANT_POT);
        addDrop(ModBlocks.BOOKS);

        addDrop(ModBlocks.PC_TOWER_GLASS);

        addDrop(ModBlocks.CEILING_FAN);
        addDrop(ModBlocks.BLACK_GAMING_CHAIR);
        addDrop(ModBlocks.WHITE_GAMING_CHAIR);

        addDrop(ModBlocks.TOILET);

        addDrop(ModBlocks.CEILING_FAN_B);
        addDrop(ModBlocks.BLACK_SOFA);
        addDrop(ModBlocks.MIDI_KEYBOARD_CONTROLLER);
        addDrop(ModBlocks.WOOD_MEDIUM_TV_STAND);
        addDrop(ModBlocks.WOOD_MEDIUM_3_DRAWER_DRESSER);
        addDrop(ModBlocks.WOOD_MEDIUM_CHAIR);
        addDrop(ModBlocks.WOOD_MEDIUM_COFFEE_TABLE);
        addDrop(ModBlocks.WOOD_MEDIUM_DESK);
        addDrop(ModBlocks.WOOD_MEDIUM_STANDING_DESK);
        addDrop(ModBlocks.WOOD_MEDIUM_STANDING_DESK_B);
        addDrop(ModBlocks.WOOD_MEDIUM_STRIPED_WALL);
        addDrop(ModBlocks.WOOD_MEDIUM_TABLE);
        addDrop(ModBlocks.WOOD_MEDIUM_KITCHEN_CABINET_BOTTOM);
        addDrop(ModBlocks.WOOD_MEDIUM_KITCHEN_CABINET_BOTTOM_WITH_SINK);
        addDrop(ModBlocks.WOOD_MEDIUM_KITCHEN_CABINET_BOTTOM_2);
        addDrop(ModBlocks.WOOD_MEDIUM_KITCHEN_CABINET_BOTTOM_2_EXTRA);
        addDrop(ModBlocks.WOOD_MEDIUM_KITCHEN_CABINET_BOTTOM_B);
        addDrop(ModBlocks.WOOD_MEDIUM_KITCHEN_CABINET_BOTTOM_B_WITH_SINK);
        addDrop(ModBlocks.WOOD_MEDIUM_KITCHEN_CABINET_BOTTOM_B_2);
        addDrop(ModBlocks.WOOD_MEDIUM_KITCHEN_DRAWERS);
        addDrop(ModBlocks.WOOD_MEDIUM_KITCHEN_DRAWERS_B);
        addDrop(ModBlocks.WOOD_MEDIUM_KITCHEN_CABINET_TOP);
        addDrop(ModBlocks.WOOD_MEDIUM_KITCHEN_CABINET_TOP_B);

        addDrop(ModBlocks.COMPUTER_CASE);
        addDrop(ModBlocks.PC_ADDED_1);
        addDrop(ModBlocks.PC_ADDED_2);
        addDrop(ModBlocks.PC_ADDED_3);
        addDrop(ModBlocks.PC_ADDED_4);
        addDrop(ModBlocks.PC_ADDED_5);
        addDrop(ModBlocks.PC_ADDED_6);
        addDrop(ModBlocks.PC_ADDED_7);
        addDrop(ModBlocks.PC_ADDED_8);
        addDrop(ModBlocks.PC_ADDED_9);
        addDrop(ModBlocks.PC_ADDED_10);
        addDrop(ModBlocks.PC_ADDED_11);

        addDrop(ModBlocks.BLACK_CHAIR);
        addDrop(ModBlocks.BLACK_COFFEE_TABLE);
        addDrop(ModBlocks.BLACK_3_DRAWER_DRESSER);
        addDrop(ModBlocks.WOOD_LIGHT_DRAWER_SINGLE);
        addDrop(ModBlocks.WOOD_MEDIUM_DRAWER_SINGLE);
        addDrop(ModBlocks.BLACK_DRAWER_SINGLE);
        addDrop(ModBlocks.WHITE_DRAWER_SINGLE);
        addDrop(ModBlocks.BLACK_DESK);
        addDrop(ModBlocks.BLACK_TV_STAND);
        addDrop(ModBlocks.BLACK_DESK_COLUMN);
        addDrop(ModBlocks.WHITE_DESK_COLUMN);
        addDrop(ModBlocks.BLACK_VERTICAL_BLINDS);
        addDrop(ModBlocks.WOOD_LIGHT_CEILING_FAN_BLACK);
        addDrop(ModBlocks.WOOD_MEDIUM_CEILING_FAN_BLACK);
        addDrop(ModBlocks.BLACK_CEILING_FAN_BLACK);
        addDrop(ModBlocks.WHITE_CEILING_FAN_BLACK);
        addDrop(ModBlocks.WOOD_LIGHT_CEILING_FAN_WHITE);
        addDrop(ModBlocks.WOOD_MEDIUM_CEILING_FAN_WHITE);
        addDrop(ModBlocks.BLACK_CEILING_FAN_WHITE);
        addDrop(ModBlocks.WHITE_CEILING_FAN_WHITE);
        addDrop(ModBlocks.WHITE_SOFA);
        addDrop(ModBlocks.WOOD_LIGHT_COMPARTMENT_STORAGE_CABINET);
        addDrop(ModBlocks.WOOD_MEDIUM_COMPARTMENT_STORAGE_CABINET);
        addDrop(ModBlocks.BLACK_COMPARTMENT_STORAGE_CABINET);
        addDrop(ModBlocks.WHITE_COMPARTMENT_STORAGE_CABINET);
        addDrop(ModBlocks.WOOD_LIGHT_KITCHEN_COMPARTMENT_STORAGE_CABINET);
        addDrop(ModBlocks.WOOD_MEDIUM_KITCHEN_COMPARTMENT_STORAGE_CABINET);
        addDrop(ModBlocks.WOOD_LIGHT_KITCHEN_COMPARTMENT_STORAGE_CABINET_B);
        addDrop(ModBlocks.WOOD_MEDIUM_KITCHEN_COMPARTMENT_STORAGE_CABINET_B);
        addDrop(ModBlocks.WHITE_VERTICAL_BLINDS);
        addDrop(ModBlocks.WOOD_LIGHT_3_DRAWER_DRESSER);
        addDrop(ModBlocks.WOOD_LIGHT_CHAIR);
        addDrop(ModBlocks.WOOD_LIGHT_COFFEE_TABLE);
        addDrop(ModBlocks.WOOD_LIGHT_DESK);
        addDrop(ModBlocks.WOOD_LIGHT_STANDING_DESK);
        addDrop(ModBlocks.WOOD_LIGHT_STANDING_DESK_B);
        addDrop(ModBlocks.WOOD_LIGHT_KITCHEN_CABINET_BOTTOM);
        addDrop(ModBlocks.WOOD_LIGHT_KITCHEN_CABINET_BOTTOM_WITH_SINK);
        addDrop(ModBlocks.WOOD_LIGHT_KITCHEN_CABINET_BOTTOM_2);
        addDrop(ModBlocks.WOOD_LIGHT_KITCHEN_CABINET_BOTTOM_2_EXTRA);
        addDrop(ModBlocks.WOOD_LIGHT_KITCHEN_CABINET_BOTTOM_B);
        addDrop(ModBlocks.WOOD_LIGHT_KITCHEN_CABINET_BOTTOM_B_WITH_SINK);
        addDrop(ModBlocks.WOOD_LIGHT_KITCHEN_CABINET_BOTTOM_B_2);
        addDrop(ModBlocks.WOOD_LIGHT_KITCHEN_DRAWERS);
        addDrop(ModBlocks.WOOD_LIGHT_KITCHEN_DRAWERS_B);
        addDrop(ModBlocks.WOOD_LIGHT_KITCHEN_CABINET_TOP);
        addDrop(ModBlocks.WOOD_LIGHT_KITCHEN_CABINET_TOP_B);
        addDrop(ModBlocks.BLACK_COMPUTER_MOUSE);
        addDrop(ModBlocks.BLACK_KEYBOARD);
    }
}
